on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build flask app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Build an image
        uses: docker/build-push-action@v4
        with:
            context: .
            file: ./Dockerfile
            push: false
            tags: flask-demo:latest
